add new functions and tests
KulakDmitry/react-practice pull request #2
Opened 2022-04-14 10:51 UTC by KulakDmitry

2022-04-16 11:04 UTC, alexanderchernetsky requested changes

2022-04-16 11:04 UTC, alexanderchernetsky commented on src/utils/calculateDistanceInMilesFurlongsYards/calculateDistanceInMilesFurlongsYards.test.js
> +  it("should return empty string", () => {
Don't forget to add if/when. Should be "should return an empty string when full distance in yards is 0". Please correct it in all similar cases.

2022-04-16 11:04 UTC, alexanderchernetsky commented on src/utils/calculateDistanceInMilesFurlongsYards/calculateDistanceInMilesFurlongsYards.test.js
> +  it("should return empty string if use default parameters", () => {
No need to write this test, because it's obvious than when nothing provided to the function it will use 0 as a default parameter `fullDistanceInYards = 0`. It's in the function definition. And the next test is similar and checks what will be returned in that case.

2022-04-16 11:04 UTC, alexanderchernetsky commented on src/utils/createSearchString/createSearchString.test.js
> +  it("should match with some parameters", () => {
The word `some` is not a suitable word in this case. It's better to name this test "should return a correct search string when multiple parameters provided". Try to be as clear as possible when you write a test name. Other devs will be grateful for that :)

2022-04-16 11:04 UTC, alexanderchernetsky commented on src/utils/findEmails/findEmails.test.js
> +describe("Emails check", () => {
Please use 1 describe per 1 function. That's a commonly used best practice.

2022-04-16 11:04 UTC, alexanderchernetsky commented on src/utils/createSearchString/createSearchString.js
> +module.exports = createSearchString;
You don't need to use CommonJS module.exports. Please remove it. You need to use ES6 syntax. So export in the first string is sufficient. Correct this in all similar cases.

2022-04-16 11:04 UTC, alexanderchernetsky commented on src/utils/findEmails/findEmails.test.js
> +const string = "Sincere@april.biz hello world !! Nathan@yesenia.net";
Please move string inside the describe. Also, if you're using it in a test, then by convention it should start from "mock". E.g. `mockStringWithEmails`.

2022-04-16 11:04 UTC, alexanderchernetsky commented on src/utils/findEmails/findEmails.test.js
> +  it("should findEmails", () => {
Please write proper names for your tests. In this case it can be "should return the first found email when provided a string with multiple emails." Also it makes sense to test the case when the string doesn't contain any emails.

2022-04-16 11:04 UTC, alexanderchernetsky commented on src/utils/getNumberOfRaceRunners/getNumberOfRaceRunners.test.js
> +describe("getNumberOfRaceRunners", () => {
Please add a test to check that this fn doesn't count non runners.

2022-04-18 08:58 UTC, KulakDmitry commented on src/utils/calculateDistanceInMilesFurlongsYards/calculateDistanceInMilesFurlongsYards.test.js
> +  it("should return empty string if use default parameters", () => {
fixed

2022-04-18 09:02 UTC, KulakDmitry commented on src/utils/calculateDistanceInMilesFurlongsYards/calculateDistanceInMilesFurlongsYards.test.js
> +  it("should return empty string", () => {
fixed

2022-04-18 09:04 UTC, KulakDmitry commented on src/utils/createSearchString/createSearchString.test.js
> +  it("should match with some parameters", () => {
fixed

2022-04-18 09:08 UTC, KulakDmitry commented on src/utils/createSearchString/createSearchString.js
> +module.exports = createSearchString;
fixed

2022-04-18 09:14 UTC, KulakDmitry commented on src/utils/findEmails/findEmails.test.js
> +  it("should findEmails", () => {
fixed

2022-04-18 11:22 UTC, KulakDmitry commented on src/utils/findEmails/findEmails.test.js
> +const string = "Sincere@april.biz hello world !! Nathan@yesenia.net";
fixed

2022-04-18 11:22 UTC, KulakDmitry commented on src/utils/findEmails/findEmails.test.js
> +describe("Emails check", () => {
fixed

2022-04-18 12:42 UTC, KulakDmitry commented on src/utils/getNumberOfRaceRunners/getNumberOfRaceRunners.test.js
> +describe("getNumberOfRaceRunners", () => {
fixed

2022-04-23 15:12 UTC, merged